language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_install:
  - composer self-update

install:
  #- composer install --no-interaction --prefer-source
  - composer install --no-interaction --prefer-source --ignore-platform-reqs # --ignore-platform-reqs because of consistence/coding-standard

script:
  - composer phpcs
  - composer phpstan
