language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - composer phpcs
  - composer phpstan
