name: build

on: [push, pull_request]

jobs:
  run:
    runs-on: 'ubuntu-18.04'

    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-suggest

      - name: Run phpcs
        run: composer phpcs

      - name: Run phpstan
        run: composer phpstan
